on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
    build-linux:
        name: Releasing Linux
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install GCC multilib
              run: |
                  sudo apt-get install gcc-multilib

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build project
              run: |
                  bash ./scripts/release.sh linux- 

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      release/rustbase-linux-x64.zip
                      release/rustbase-linux-x86.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-windows-x64:
        name: Releasing Windows
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install MinGW
              uses: egor-tensin/setup-mingw@v2

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build project
              run: |
                  bash ./scripts/release.sh windows-x64

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      release/rustbase-windows-x64.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    build-windows-x86:
        name: Releasing Windows
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install MinGW
              uses: egor-tensin/setup-mingw@v2
              with:
                platform: x86

            - name: Install latest rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build project
              run: |
                  bash ./scripts/release.sh windows-x86

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      release/rustbase-windows-x86.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
